        location / {
            # Generate a unique nonce per request ($request_id) and send it in the CSP header
            add_header Content-Security-Policy "
		default-src 'self'; 
		script-src 'self' 'nonce-$request_id' https://challenges.cloudflare.com; 
		style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; 
		font-src https://fonts.gstatic.com; 
		img-src 'self' https://raw.githubusercontent.com https://*.githubusercontent.com https://github.com https://*.amazonaws.com data:; 
		connect-src 'self' https://api.github.com; frame-src https://challenges.cloudflare.com;";
            root /opt/kula-web;
            index index.html;
        }
